Nav Bar Update
Harvela/DugAssistant-Langing pull request #3
Opened 2024-11-11 15:47 UTC by lemoissonM

2024-11-14 12:19 UTC, Hoppy5 commented
this is the modification of the navbar

2024-11-14 19:20 UTC, ciraganenicole requested changes
Good job so far 🎊  
Still some minor changes and you will be done. Keep it up 😃

2024-11-14 19:20 UTC, ciraganenicole commented on src/navigation/Navbar.tsx
Cette partie doit etre cliquable, un lien vers la premiere page

2024-11-14 19:20 UTC, ciraganenicole commented on src/navigation/Navbar.tsx
Quand le bg devient black on hover, le border-white ne doit plus apparaitre. On va avoir un button avec le background black et text green sans border

2024-11-14 19:20 UTC, ciraganenicole commented on src/navigation/Navbar.tsx
>              </Link>
On hover, augmente un peux le padding x (px-4) pour un peu plus d'esthetique

2024-11-15 10:17 UTC, Hoppy5 commented
Bonjour Nicky. J’ai déjà ajouté les modifications

Le jeu. 14 nov. 2024 à 21:20, Ciragane Nicole ***@***.***> a
écrit :

> ***@***.**** requested changes on this pull request.
>
> Good job so far 🎊
> Still some minor changes and you will be done. Keep it up 😃
> ------------------------------
>
> In src/navigation/Navbar.tsx
> <https://github.com/Harvela/DugAssistant-Langing/pull/3#discussion_r1842761557>
> :
>
> >          <div className="flex flex-row items-center gap-2">
>            <img
> -            src="/logo1.jpg"
> +            src="/logo192.png"
>              alt="logo1"
> -            className="h-12 w-auto text-white"
> +            className="h-8 w-auto rounded-[8px] text-white"
>            />
> -          <p className="text-[24px] font-semibold text-white">DugAssistant</p>
> +          <p className="text-[18px] font-semibold text-white">DugAssistant</p>
>          </div>
>
>
> Cette partie doit etre cliquable, un lien vers la premiere page
> ------------------------------
>
> In src/navigation/Navbar.tsx
> <https://github.com/Harvela/DugAssistant-Langing/pull/3#discussion_r1842764945>
> :
>
> > +          className="relative rounded-md border-[2px] border-white px-6 py-2 text-[13px] font-medium text-white shadow-sm shadow-primary-400 hover:bg-black hover:text-primary-500"
>          >
>            <span>Se connecter</span>
>          </a>
>        </div>
>
>
> Quand le bg devient black on hover, le border-white ne doit plus
> apparaitre. On va avoir un button avec le background black et text green
> sans border
> ------------------------------
>
> In src/navigation/Navbar.tsx
> <https://github.com/Harvela/DugAssistant-Langing/pull/3#discussion_r1842767900>
> :
>
> >                href={navItem.link}
> -              className="text-[18px] font-medium text-white"
> +              className={`rounded-[5px] p-2 text-[14px] font-medium text-white transition duration-300 ${
> +                router.pathname === navItem.link
> +                  ? 'bg-black bg-opacity-10' // Applique le style actif
> +                  : 'hover:bg-black hover:bg-opacity-10' // Applique un effet au survol
> +              }`}
>              >
>                {navItem.name}
>              </Link>
>
> On hover, augmente un peux le padding x (px-4) pour un peu plus
> d'esthetique
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Harvela/DugAssistant-Langing/pull/3#pullrequestreview-2436988182>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BEO5X7YMVUUGOGTUTE5VAGL2ATZYRAVCNFSM6AAAAABRSDYD5SVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDIMZWHE4DQMJYGI>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-11-16 08:44 UTC, ciraganenicole approved these changes
Good job Hope 🎊

2024-11-16 08:45 UTC, merged